const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const page=document.body.dataset.page||'dashboard';
const routes={image:'CHUPWEB.html',ocr:'OCR.html',data:'NEN.html',accounts:'GMAIL.html',translate:'Vi-translate.html'};
const cfg={
 dashboard:{title:'Dashboard',sub:'Your personal workspace',tools:[['🖼','Image Lab','Images'],['⌕','OCR Studio','Text recognition'],['◇','Data Lab','Data utilities'],['◎','Accounts','Account links'],['文','Translate','Translation']]},
 image:{title:'Image Lab',sub:'Edit and export images',tools:[['🖼','Image Editor','Brightness, contrast, saturation, rotate, flip']]},
 ocr:{title:'OCR Studio',sub:'Extract text from images',tools:[['⌕','OCR Studio','English / Vietnamese recognition']]},
 data:{title:'Data Lab',sub:'Small utilities for everyday data',tools:[['🔐','Base64','Encode / decode'],['🔗','URL','Encode / decode'],['{}','JSON','Format / minify / validate'],['#','SHA-256','Hash with Web Crypto'],['🆔','UUID','Generate UUID v4'],['🔢','Text Counter','Characters, words, lines'],['🕒','Timestamp','Unix time / date'],['⇄','CSV ↔ JSON','Convert both ways'],['🗜','GZIP','Compress text']]},
 accounts:{title:'Accounts',sub:'Local account links — passwords are never stored',tools:[['◎','Account Manager','Name, username and login URL']]},
 translate:{title:'Translate',sub:'Online text translation',tools:[['文','Translator','Source and target language']]}
};
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function nav(){$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function go(p){if(p==='dashboard')location.href='index.html';else if(routes[p])location.href=routes[p]}
function renderTools(){const data=cfg[page]||cfg.dashboard;$('#title').textContent=data.title;$('#subtitle').textContent=data.sub;const list=$('#tools');list.innerHTML=data.tools.map((t,i)=>`<button type="button" class="feature ${i===0?'active':''}" data-tool="${esc(t[1])}" aria-label="${esc(t[1])}"><span class="ficon">${t[0]}</span><span><b>${esc(t[1])}</b><small>${esc(t[2])}</small></span></button>`).join('');$$('.feature').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool));let last=null;try{last=localStorage.getItem('dynamicHub:lastTool:'+page)}catch(_){}selectTool(data.tools.some(t=>t[1]===last)?last:data.tools[0][1])}
function selectTool(name){$$('.feature').forEach(x=>x.classList.toggle('active',x.dataset.tool===name));$('#toolTitle').textContent=name;$('#toolStage').innerHTML=toolUI(name);bind(name);updateInspector(name);try{localStorage.setItem('dynamicHub:lastTool:'+page,name)}catch(_){}}
function updateInspector(name){const b=$('#inspectorBody');const map={
'Image Lab':`<div class="group"><div class="label">MODULE</div><div class="result">Image editing workspace</div></div>`,
'OCR Studio':`<div class="group"><div class="label">MODULE</div><div class="result">OCR workspace</div></div>`,
'Data Lab':`<div class="group"><div class="label">MODULE</div><div class="result">Data utilities workspace</div></div>`,
'Accounts':`<div class="group"><div class="label">MODULE</div><div class="result">Local account manager</div></div>`,
'Translate':`<div class="group"><div class="label">MODULE</div><div class="result">Translation workspace</div></div>`,
'Image Editor':`<div class="group"><div class="label">IMAGE</div><div id="imageInfo" class="result">No image selected.</div></div><div class="group"><div class="label">ADJUSTMENTS</div><div class="label">Brightness <span id="ibv">100%</span></div><input id="ib" type="range" min="0" max="200" value="100"><div class="label">Contrast <span id="icv">100%</span></div><input id="ic" type="range" min="0" max="200" value="100"><div class="label">Saturation <span id="isv">100%</span></div><input id="is" type="range" min="0" max="200" value="100"></div>`,
'OCR Studio':`<div class="group"><div class="label">LANGUAGE</div><select id="insOcrLang"><option value="eng">English</option><option value="vie">Vietnamese</option><option value="eng+vie">English + Vietnamese</option></select></div><div class="group"><div class="label">ENGINE</div><div class="result">Tesseract.js v5 · runs in browser</div></div>`,
'Translator':`<div class="group"><div class="label">LANGUAGES</div><div class="result">Source and target are selected in the workspace.</div></div><div class="group"><div class="label">NETWORK</div><div class="result">Requires Internet access for translation.</div></div>`,
'Account Manager':`<div class="group"><div class="label">STORAGE</div><div class="result">Browser LocalStorage</div></div><div class="group"><div class="label">SECURITY</div><div class="result">Passwords are never saved.</div></div>`};
b.innerHTML=map[name]||`<div class="group"><div class="label">TOOL</div><div class="result">Ready</div></div>`;
if(name==='Image Editor')['ib','ic','is'].forEach(id=>$('#'+id).oninput=()=>{const a={ib:['ibv'],ic:['icv'],is:['isv']}[id];$('#'+a[0]).textContent=$('#'+id).value+'%';applyImage()});
if(name==='OCR Studio')$('#insOcrLang').onchange=e=>{const x=$('#ocrLang');if(x)x.value=e.target.value};
}
function toolUI(n){
if(page==='dashboard'){const map={'Image Lab':['image','Edit images inside the workspace'],'OCR Studio':['ocr','Extract text from images'],'Data Lab':['data','Encode, hash and convert data'],'Accounts':['accounts','Manage account links locally'],'Translate':['translate','Translate text online']};const m=map[n];return `<div class="tool-work dashboard-launch"><div class="launch-mark">${n==='Translate'?'文':n==='Image Lab'?'🖼':n==='OCR Studio'?'⌕':n==='Data Lab'?'◇':'◎'}</div><h2>${esc(n)}</h2><p>${m[1]}</p><button class="btn primary" onclick="go('${m[0]}')">Open ${esc(n)}</button></div>`}
if(n==='Image Editor')return `<div class="tool-work"><div class="drop" id="imgDrop"><strong>Drop an image here</strong><span>PNG · JPG · WEBP</span><label class="btn primary">Choose image<input id="imgFile" type="file" accept="image/*"></label></div><div id="imgWork" hidden><div class="image-frame"><img id="imgPreview" class="preview" alt="Selected image"></div><div class="toolbar"><button class="btn" id="rot">↻ Rotate</button><button class="btn" id="flip">↔ Flip</button><button class="btn" id="gray">Grayscale</button><button class="btn" id="resetImage">Reset</button><button class="btn primary" id="savePng">Export PNG</button><button class="btn" id="saveWebp">Export WebP</button></div></div></div>`;
if(n==='OCR Studio')return `<div class="tool-work"><div class="toolbar"><label class="btn primary">Choose image<input id="ocrFile" type="file" accept="image/*"></label><select id="ocrLang"><option value="eng">English</option><option value="vie">Vietnamese</option><option value="eng+vie">English + Vietnamese</option></select><button class="btn primary" id="runOCR">Run OCR</button></div><img id="ocrPreview" class="preview" hidden alt="OCR source"><textarea id="ocrText" placeholder="OCR result..."></textarea><div class="toolbar"><button class="btn" id="copyOCR">Copy</button><button class="btn" id="downloadOCR">Export TXT</button><button class="btn danger" id="clearOCR">Clear</button></div></div>`;
if(['Base64','URL','JSON','SHA-256','UUID','Text Counter','Timestamp','CSV ↔ JSON','GZIP'].includes(n))return `<div class="tool-work"><textarea id="dataIn" placeholder="Input..."></textarea><div class="toolbar">${buttonsFor(n)}</div><div class="label">OUTPUT</div><div id="dataOut" class="result"></div></div>`;
if(n==='Account Manager')return `<div class="tool-work"><div class="row"><input id="accName" placeholder="Service / name"><input id="accUser" placeholder="Username / email"></div><input id="accUrl" class="field" placeholder="Login URL (https://...)" style="margin-top:8px"><div class="toolbar"><button class="btn primary" id="addAcc">Save account</button><button class="btn" id="exportAcc">Backup JSON</button><label class="btn">Restore<input id="importAcc" type="file" accept=".json"></label></div><div class="label">SAVED ACCOUNTS</div><div id="accList"></div></div>`;
if(n==='Translator')return `<div class="tool-work"><div class="toolbar"><select id="from"><option value="vi">Vietnamese</option><option value="en">English</option><option value="ja">Japanese</option><option value="ko">Korean</option><option value="zh">Chinese</option></select><button class="btn" id="swap">⇄</button><select id="to"><option value="en">English</option><option value="vi">Vietnamese</option><option value="ja">Japanese</option><option value="ko">Korean</option><option value="zh">Chinese</option></select></div><textarea id="trIn" placeholder="Type text..."></textarea><button class="btn primary" id="translate">Translate</button><textarea id="trOut" readonly placeholder="Translation..."></textarea><div class="toolbar"><button class="btn" id="copyTr">Copy</button><button class="btn danger" id="clearTr">Clear</button></div></div>`;
return `<div class="empty">No workspace.</div>`}
function buttonsFor(n){if(n==='Base64'||n==='URL')return `<button class="btn primary" id="enc">Encode</button><button class="btn" id="dec">Decode</button>`;if(n==='JSON')return `<button class="btn primary" id="format">Format + Validate</button><button class="btn" id="minify">Minify</button>`;if(n==='SHA-256')return `<button class="btn primary" id="hash">SHA-256</button>`;if(n==='UUID')return `<button class="btn primary" id="uuid">Generate</button>`;if(n==='Text Counter')return `<button class="btn primary" id="count">Count</button>`;if(n==='Timestamp')return `<button class="btn primary" id="now">Now</button><button class="btn" id="date">From timestamp</button>`;if(n==='CSV ↔ JSON')return `<button class="btn primary" id="csvjson">CSV → JSON</button><button class="btn" id="jsoncsv">JSON → CSV</button>`;return `<button class="btn primary" id="gzip">GZIP</button>`}
function bind(n){if(n==='Image Editor')bindImage();if(n==='OCR Studio')bindOCR();if(['Base64','URL','JSON','SHA-256','UUID','Text Counter','Timestamp','CSV ↔ JSON','GZIP'].includes(n))bindData(n);if(n==='Account Manager')bindAccounts();if(n==='Translator')bindTranslate()}
let imageState={src:'',rotation:0,flip:false,gray:false};
function applyImage(){const img=$('#imgPreview');if(!img)return;const b=$('#ib')?.value||100,c=$('#ic')?.value||100,s=$('#is')?.value||100;img.style.filter=`brightness(${b}%) contrast(${c}%) saturate(${s}%) grayscale(${imageState.gray?1:0})`;img.style.transform=`rotate(${imageState.rotation}deg) scaleX(${imageState.flip?-1:1})`}
function bindImage(){const f=$('#imgFile'),drop=$('#imgDrop');const open=file=>{if(!file||!file.type.startsWith('image/'))return toast('Please choose an image');const r=new FileReader();r.onload=e=>{imageState={src:e.target.result,rotation:0,flip:false,gray:false};$('#imgPreview').src=e.target.result;drop.hidden=true;$('#imgWork').hidden=false;const info=$('#imageInfo');if(info)info.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;applyImage()};r.readAsDataURL(file)};f.onchange=()=>open(f.files[0]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag') }));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag') }));drop.addEventListener('drop',e=>open(e.dataTransfer.files[0]));window.__rot=0;window.__flip=false;$('#rot').onclick=()=>{imageState.rotation=(imageState.rotation+90)%360;applyImage()};$('#flip').onclick=()=>{imageState.flip=!imageState.flip;applyImage()};$('#gray').onclick=()=>{imageState.gray=!imageState.gray;applyImage()};$('#resetImage').onclick=()=>{imageState.rotation=0;imageState.flip=false;imageState.gray=false;['ib','ic','is'].forEach(id=>{if($('#'+id))$('#'+id).value=100});['ibv','icv','isv'].forEach(id=>{if($('#'+id))$('#'+id).textContent='100%'});applyImage()};function save(type){if(!imageState.src)return;const im=new Image();im.onload=()=>{const cv=document.createElement('canvas'),ctx=cv.getContext('2d'),rad=imageState.rotation*Math.PI/180,w=im.naturalWidth,h=im.naturalHeight;cv.width=imageState.rotation%180?h:w;cv.height=imageState.rotation%180?w:h;ctx.translate(cv.width/2,cv.height/2);ctx.rotate(rad);ctx.scale(imageState.flip?-1:1,1);ctx.filter=`brightness(${$('#ib').value}%) contrast(${$('#ic').value}%) saturate(${$('#is').value}%) grayscale(${imageState.gray?1:0})`;ctx.drawImage(im,-w/2,-h/2);cv.toBlob(blob=>downloadBlob(`dynamic-hub-image.${type==='image/webp'?'webp':'png'}`,blob),type)};im.src=imageState.src}$('#savePng').onclick=()=>save('image/png');$('#saveWebp').onclick=()=>save('image/webp')}
function bindOCR(){const f=$('#ocrFile');f.onchange=()=>{const file=f.files[0];if(file){const r=new FileReader();r.onload=e=>{$('#ocrPreview').src=e.target.result;$('#ocrPreview').hidden=false};r.readAsDataURL(file)}};$('#runOCR').onclick=async()=>{if(!f.files[0])return toast('Choose an image first');$('#runOCR').disabled=true;$('#runOCR').textContent='Recognizing…';try{if(!window.Tesseract){await loadScript('https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js')}const lang=$('#ocrLang').value;const r=await Tesseract.recognize(f.files[0],lang);$('#ocrText').value=r.data.text.trim()}catch(e){$('#ocrText').value='OCR failed. Check your Internet connection or language data.'}finally{$('#runOCR').disabled=false;$('#runOCR').textContent='Run OCR'}};$('#copyOCR').onclick=()=>copy($('#ocrText').value);$('#downloadOCR').onclick=()=>downloadText('ocr-result.txt',$('#ocrText').value);$('#clearOCR').onclick=()=>{$('#ocrText').value='';$('#ocrPreview').hidden=true;f.value=''}}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function bindData(n){const i=$('#dataIn'),o=$('#dataOut');const out=x=>o.textContent=typeof x==='string'?x:JSON.stringify(x,null,2);if(n==='Base64'){const enc=s=>btoa(unescape(encodeURIComponent(s))),dec=s=>decodeURIComponent(escape(atob(s)));$('#enc').onclick=()=>{try{out(enc(i.value))}catch(e){out('Invalid input')}};$('#dec').onclick=()=>{try{out(dec(i.value))}catch(e){out('Invalid Base64')}}}if(n==='URL'){const enc=encodeURIComponent,dec=decodeURIComponent;$('#enc').onclick=()=>out(enc(i.value));$('#dec').onclick=()=>{try{out(dec(i.value))}catch(e){out('Invalid URL encoding')}}}if(n==='JSON'){$('#format').onclick=()=>{try{out(JSON.stringify(JSON.parse(i.value),null,2))}catch(e){out('Invalid JSON')}};$('#minify').onclick=()=>{try{out(JSON.stringify(JSON.parse(i.value)))}catch(e){out('Invalid JSON')}}}if(n==='SHA-256')$('#hash').onclick=async()=>{try{out(await sha(i.value))}catch(e){out('Web Crypto is unavailable in this context')}};if(n==='UUID')$('#uuid').onclick=()=>{try{out(crypto.randomUUID?crypto.randomUUID():([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16)))}catch(e){out('UUID generation unavailable')}};if(n==='Text Counter')$('#count').onclick=()=>{const s=i.value;out(`Characters: ${[...s].length}\nWords: ${s.trim()?s.trim().split(/\s+/).length:0}\nLines: ${s?s.split(/\n/).length:0}`)};if(n==='Timestamp'){$('#now').onclick=()=>out(String(Math.floor(Date.now()/1000)));$('#date').onclick=()=>{const v=i.value.trim(),num=Number(v);if(!v||!Number.isFinite(num))return out('Enter a Unix timestamp in seconds');const d=new Date(num*1000);out(Number.isNaN(d.getTime())?'Invalid timestamp':d.toLocaleString())}}if(n==='CSV ↔ JSON'){$('#csvjson').onclick=()=>{try{out(csvToJson(i.value))}catch(e){out('Invalid CSV')}};$('#jsoncsv').onclick=()=>{try{out(jsonToCsv(JSON.parse(i.value)))}catch(e){out('Expected a JSON array of objects')}}}if(n==='GZIP')$('#gzip').onclick=async()=>{try{if(!('CompressionStream'in window))throw 0;const cs=new CompressionStream('gzip'),w=cs.writable.getWriter();w.write(new TextEncoder().encode(i.value));w.close();const blob=new Blob([await new Response(cs.readable).arrayBuffer()],{type:'application/gzip'});downloadBlob('dynamic-hub.txt.gz',blob);out('GZIP file exported.')}catch(e){out('GZIP is not supported in this browser.')}}}
async function sha(s){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function parseCSV(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const c=s[i],n=s[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';continue}cell+=c}if(cell!==''||row.length){row.push(cell);rows.push(row)}return rows.filter(r=>r.some(x=>x.trim()!==''))}
function csvToJson(s){const rows=parseCSV(s);if(rows.length<2)throw 0;const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,j)=>[k,r[j]??''])))}
function jsonToCsv(a){if(!Array.isArray(a)||!a.length||a.some(x=>!x||typeof x!=='object'||Array.isArray(x)))throw 0;const h=[...new Set(a.flatMap(x=>Object.keys(x)))];const escCSV=v=>{const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s};return [h.map(escCSV).join(','),...a.map(x=>h.map(k=>escCSV(x[k])).join(','))].join('\n')}
function bindAccounts(){const key='dynamicHubAccounts';const get=()=>{try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};const render=()=>{$('#accList').innerHTML=get().map((a,i)=>`<div class="account"><div><b>${esc(a.name)}</b><small>${esc(a.user)} · <span class="pill">local</span></small></div><div class="toolbar"><button class="btn" data-open="${i}">Open</button><button class="btn danger" data-del="${i}">Delete</button></div></div>`).join('')||'<div class="empty">No accounts saved.</div>';$$('[data-open]').forEach(b=>b.onclick=()=>{const a=get()[+b.dataset.open];if(a?.url)window.open(a.url,'_blank','noopener,noreferrer');else toast('No login URL saved')});$$('[data-del]').forEach(b=>b.onclick=()=>{const a=get();a.splice(+b.dataset.del,1);localStorage.setItem(key,JSON.stringify(a));render()})};$('#addAcc').onclick=()=>{const name=$('#accName').value.trim(),user=$('#accUser').value.trim(),url=$('#accUrl').value.trim();if(!name||!user)return toast('Name and username required');if(url&&!/^https?:\/\//i.test(url))return toast('Login URL must start with http:// or https://');const a=get();if(a.some(x=>String(x.user||'').trim().toLowerCase()===user.toLowerCase()))return toast('Username already exists');a.push({name,user,url});localStorage.setItem(key,JSON.stringify(a));$('#accName').value='';$('#accUser').value='';$('#accUrl').value='';render();toast('Account saved')};$('#exportAcc').onclick=()=>downloadText('dynamic-hub-accounts.json',JSON.stringify(get(),null,2));$('#importAcc').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const a=JSON.parse(await file.text());if(!Array.isArray(a))throw 0;localStorage.setItem(key,JSON.stringify(a.map(x=>({name:String(x.name||''),user:String(x.user||''),url:String(x.url||'')})).filter(x=>x.name&&x.user)));render();toast('Restored')}catch(_){toast('Invalid backup')}finally{e.target.value=''}};render()}
function bindTranslate(){$('#swap').onclick=()=>{const f=$('#from'),t=$('#to');[f.value,t.value]=[t.value,f.value];if($('#trIn').value||$('#trOut').value)[$('#trIn').value,$('#trOut').value]=[$('#trOut').value,$('#trIn').value]};$('#translate').onclick=async()=>{const q=$('#trIn').value.trim();if(!q)return toast('Enter text first');if($('#from').value===$('#to').value)return $('#trOut').value=q;$('#translate').disabled=true;$('#translate').textContent='Translating…';$('#trOut').value='';try{const u=`https://api.mymemory.translated.net/get?q=${encodeURIComponent(q)}&langpair=${$('#from').value}|${$('#to').value}`;const r=await fetch(u);if(!r.ok)throw 0;const j=await r.json();$('#trOut').value=j.responseData?.translatedText||'No result'}catch(e){$('#trOut').value='Translation service unavailable.'}finally{$('#translate').disabled=false;$('#translate').textContent='Translate'}};$('#copyTr').onclick=()=>copy($('#trOut').value);$('#clearTr').onclick=()=>{$('#trIn').value='';$('#trOut').value=''}}
function copy(s){if(!s)return toast('Nothing to copy');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(s).then(()=>toast('Copied')).catch(()=>toast('Copy failed'));else toast('Clipboard unavailable')}
function downloadText(name,text){downloadBlob(name,new Blob([text],{type:'text/plain;charset=utf-8'}))}
function downloadBlob(name,blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),500)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function init(){nav();renderTools();const search=$('#search');search.oninput=e=>{const q=e.target.value.toLowerCase().trim();const items=$$('.feature');let shown=0;items.forEach(b=>{const hit=!q||b.textContent.toLowerCase().includes(q);b.hidden=!hit;if(hit)shown++});let empty=$('#searchEmpty');if(!shown&&items.length){if(!empty){empty=document.createElement('div');empty.id='searchEmpty';empty.className='empty search-empty';empty.textContent='No matching tools.';$('#tools').appendChild(empty)}empty.hidden=false}else if(empty)empty.hidden=true};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus()}if(e.key==='Escape'&&document.activeElement===search){search.value='';search.dispatchEvent(new Event('input'));search.blur()}})}
window.go=go;document.addEventListener('DOMContentLoaded',init);
