import {toast} from '../core/toast.js';
let source=null, rotation=0, flipX=1, gray=false;
const file=document.querySelector('#imgFile'),drop=document.querySelector('#imgDrop'),img=document.querySelector('#imgPreview');
const b=document.querySelector('#ib'),c=document.querySelector('#ic'),s=document.querySelector('#is');
function render(){if(!source)return;img.src=source;img.style.filter=`brightness(${b?.value||100}%) contrast(${c?.value||100}%) saturate(${s?.value||100}%) grayscale(${gray?1:0})`;img.style.transform=`rotate(${rotation}deg) scaleX(${flipX})`}
function load(f){if(!f?.type.startsWith('image/'))return toast('Please choose an image');const r=new FileReader();r.onload=()=>{source=r.result;document.querySelector('#imgWork').hidden=false;drop.hidden=true;render();document.querySelector('#imageInfo').textContent=`${f.name} · ${(f.size/1024).toFixed(1)} KB`};r.readAsDataURL(f)}
file?.addEventListener('change',e=>load(e.target.files[0]));['dragover','dragenter'].forEach(x=>drop?.addEventListener(x,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(x=>drop?.addEventListener(x,e=>{e.preventDefault();drop.classList.remove('drag')}));drop?.addEventListener('drop',e=>load(e.dataTransfer.files[0]));[b,c,s].forEach(x=>x?.addEventListener('input',render));
document.querySelector('#rot')?.addEventListener('click',()=>{rotation=(rotation+90)%360;render()});document.querySelector('#flip')?.addEventListener('click',()=>{flipX*=-1;render()});document.querySelector('#gray')?.addEventListener('click',()=>{gray=!gray;render()});document.querySelector('#resetImage')?.addEventListener('click',()=>{rotation=0;flipX=1;gray=false;if(b)b.value=100;if(c)c.value=100;if(s)s.value=100;render()});
function exportImage(type){if(!source)return toast('Choose an image first');const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),image=new Image();image.onload=()=>{const swap=Math.abs(rotation)%180===90;canvas.width=swap?image.height:image.width;canvas.height=swap?image.width:image.height;ctx.filter=`brightness(${b?.value||100}%) contrast(${c?.value||100}%) saturate(${s?.value||100}%) grayscale(${gray?1:0})`;ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(rotation*Math.PI/180);ctx.scale(flipX,1);ctx.drawImage(image,-image.width/2,-image.height/2);const a=document.createElement('a');a.download=`dynamic-hub.${type==='image/webp'?'webp':'png'}`;a.href=canvas.toDataURL(type);a.click()};image.src=source}document.querySelector('#savePng')?.addEventListener('click',()=>exportImage('image/png'));document.querySelector('#saveWebp')?.addEventListener('click',()=>exportImage('image/webp'));
